name: authentication-backend-prod

services:
  authentication-service:
    image: ghcr.io/fpt-ojt/authentication-service:latest
    container_name: authentication-service
    networks:
      - default
      - ojt_shared_network
    restart: always
    env_file:
      - ../env/authentication-service.env
    environment:
      - POSTGRESQL_HOST=auth-postgres
      - POSTGRESQL_EXTERNAL_PORT=5432
      - REDIS_HOST=auth-redis
      - REDIS_EXTERNAL_PORT=6379
      - SERVER_PORT=8081
      - RABBITMQ_URL=amqp://${RABBITMQ_ADMIN_USER:-admin}:${RABBITMQ_ADMIN_PASSWORD:-password}@rabbitmq:5672/
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "${AUTH_SERVER_PORT:-8081}:8081"
    depends_on:
      auth-postgres:
        condition: service_healthy
      auth-redis:
        condition: service_healthy

  auth-postgres:
    image: postgres:18-alpine
    container_name: ${AUTH_POSTGRES_CONTAINER_NAME:-auth-postgres}
    networks:
      - default
      - ojt_shared_network
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - auth-postgres-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-redis:
    image: redis:7-alpine
    container_name: auth-redis
    networks:
      - default
      - ojt_shared_network
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - auth-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth-postgres-data:
  auth-redis-data:

networks:
  ojt_shared_network:
    external: true
