name: ojt-backend

services:
  ojt-backend:
    image: ghcr.io/fpt-ojt/core-service:latest
    container_name: ojt-backend
    networks:
      - default
      - ojt_shared_network
    restart: always
    env_file:
      - ../env/core-service.env
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_EXTERNAL_PORT=5432
      - REDIS_HOST=redis
      - REDIS_EXTERNAL_PORT=6379
      - SERVER_PORT=8080
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    # ports:
    #   - "${SERVER_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgis/postgis:18-3.6
    container_name: ${POSTGRES_CONTAINER_NAME}
    networks:
      - default
      - ojt_shared_network
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  ojt_shared_network:
    external: true
